options:
  docker: true

pipelines:
  tags:
    10.*:
      - step:
          name: Trigger Drupal build
          script:
            - pipe: atlassian/trigger-pipeline:5.0.0
              variables:
                BITBUCKET_USERNAME: $PIPELINES_TRIGGER_USER
                BITBUCKET_APP_PASSWORD: $PIPELINES_TRIGGER_PASS
                REF_TYPE: "branch"
                REF_NAME: "10.x"
                ACCOUNT: "iconagency"
                REPOSITORY: "lagoon-drupal"
          caches:
            - docker
