# Turn off auth locally.
services:
  nginx:
    overrides:
      environment:
        BASIC_AUTH: "off"

# We'll install all our linting requirements in here.
# Feel free to modify the package.json to your requirements.
# https://docs.lando.dev/config/performance.html#configuration
excludes:
  - node_modules
